### ISSUE TITLE
Bro i use your lib but i have problem with the width

### ISSUE THREAD

**Issue by atlabiz** [JeremyFagis/dropify#72]
Bro, I use your lib but I have a problem with the width of the dropify container plz fix that.
The dropify container is getting 120% of the parent width

## I try this but not working
```css
.dropify-wrapper{
  max-width: 95% !important;
  width: 95% !important;
}
```

## And this not work

```html
<div style="width:100%;">
       <input type="file" id="category_image_update" [(ngModel)]="category_image_update" name="category_image_update" class="dropify" 
        data-default-file="" data-height="280" data-width="" data-max-width="200px"
        data-allowed-file-extensions="jpg png jpeg gif bmp" data-max-file-size-preview="2M"/>
</div>
```
